// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient } from "npm:@supabase/supabase-js@^2.93.2";
import { z } from "npm:zod@^4.4.3";
var search_products_default = defineTool({
  name: "search_products",
  title: "Search marketplace products",
  description: "Search FitConnect marketplace products (wears, equipment, supplements). Returns name, category, price in USDC, stock, and vendor id.",
  inputSchema: {
    query: z.string().trim().optional().describe("Optional text to match in product name/description."),
    category: z.enum(["wears", "equipment", "supplements", "apparel", "accessories"]).optional().describe("Optional product category filter."),
    limit: z.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("products").select("id,name,description,category,price_usdc,price_kes,stock,vendor_id,images,is_active").eq("is_active", true).limit(limit);
    if (category) q = q.eq("category", category);
    if (query) q = q.or(`name.ilike.%${query}%,description.ilike.%${query}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-vendors.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.2";
import { z as z2 } from "npm:zod@^4.4.3";
var list_vendors_default = defineTool2({
  name: "list_vendors",
  title: "List FitConnect vendors",
  description: "List verified fitness vendors on FitConnect, optionally filtered by country or city.",
  inputSchema: {
    country: z2.string().trim().optional(),
    city: z2.string().trim().optional(),
    limit: z2.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ country, city, limit }) => {
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = supabase.from("vendors_public").select("id,business_name,description,city,country,logo_url,onchain_verified,status").limit(limit);
    if (country) q = q.ilike("country", country);
    if (city) q = q.ilike("city", city);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { vendors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/platform-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var platform_info_default = defineTool3({
  name: "platform_info",
  title: "About FitConnect",
  description: "Return an overview of FitConnect: what it does, supported categories of trainers/clubs/marketplace, currencies, and booking flow.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: JSON.stringify({
          name: "FitConnect",
          summary: "Global Web3 fitness marketplace connecting clients with trainers, clubs, and fitness vendors. USDC escrow bookings on Avalanche with local-currency display.",
          trainer_categories: [
            "athletes",
            "football",
            "swimming",
            "golf",
            "gym",
            "yoga",
            "running",
            "boxing"
          ],
          club_categories: ["wellness centres", "golf clubs", "football clubs", "running clubs"],
          marketplace_categories: ["wears", "equipment", "supplements"],
          currencies: { primary: "USDC", chain: "Avalanche" },
          booking_flow: "Book trainer \u2192 funds held in escrow \u2192 session confirmed \u2192 85% to trainer, 15% platform fee."
        })
      }
    ]
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "fitconnect-mcp",
  title: "FitConnect MCP",
  version: "0.1.0",
  instructions: "Tools for FitConnect, a global fitness marketplace. Use `platform_info` for an overview, `search_products` to browse marketplace items (wears, equipment, supplements), and `list_vendors` to find verified vendors by country/city.",
  tools: [platform_info_default, search_products_default, list_vendors_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
